BOOTMAGIC_ENABLE	= no
MOUSEKEY_ENABLE		= no
EXTRAKEY_ENABLE		= yes
CONSOLE_ENABLE		= no
NKRO_ENABLE			= yes
BACKLIGHT_ENABLE	= no
MIDI_ENABLE			= no
AUDIO_ENABLE		= no
UNICODE_ENABLE		= no
BLUETOOTH_ENABLE	= no
RGBLIGHT_ENABLE		= no
SWAP_HANDS_ENABLE	= no
RGB_MATRIX_ENABLE	= no
HAPTIC_ENABLE		= no
SLEEP_LED_ENABLE	= no
OLED_DRIVER_ENABLE	= yes

BOOTLOADER 			= caterina
